name: "Cloudflare DNS-01 SSL"
description: "Uses Cloudflare's DNS api to generate an SSL certificate"
version: "1.1.0"
slug: "cloudflare-dns01-ssl"
init: false
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
map:
    - ssl:rw
options:
    cf:
        token: null
        account_id: null
        zone_id: null
    domain: null
    server: letsencrypt
    email: null
    dry: true
schema:
    cf:
        token: str
        account_id: str
        zone_id: str
    domain: str
    server: str
    email: email
    dry: bool
image: "ghcr.io/sportshead/{arch}-addon-cloudflare-dns01-ssl"
